### ISSUE TITLE
Cannot import in angular app

### ISSUE THREAD

**Issue by rnicolas** [QueenKunkun/angular-libs#1] opened 2020-09-09 17:00 UTC
After installation, when I type in app.component.ts: 

`import { SseClient } from 'angular-sse-client';`

angular compilation throws an error saying:

ERROR in Cannot read property '0' of undefined

**Comment by QueenKunkun** [comment] 2020-12-05 08:10
Not able to reproduce.
which version of angular are you using? and is it possible to locate the line of code throws?

**Comment by rnicolas** [comment] 2020-12-06 21:30
The line is that one:

`import { SseClient } from 'angular-sse-client';`

The angular version is the 10th.

**Comment by QueenKunkun** [comment] 2020-12-07 02:48
If comment out that line, and remove all the references to SseClient, then the compile error will disappear? 
I suspect the error is a run time rather than compilation error, and also not relative since the source code of sseclient rarely accessing object like obj[0]

**Comment by QueenKunkun** [comment] 2020-12-07 06:50
another cause may be: the package was downloaded incompletely.
Would you mind try a later version by running `npm update angular-sse-client`? which I just published as version `0.1.0` for some minor chanages, mainly about documentation, and a small options name change.
@rnicolas

**Comment by QueenKunkun** [comment] 2020-12-09 06:17
hi @rnicolas , I created an example code here https://github.com/QueenKunkun/angular-sse-test and still could not reproduce the problem, you can give it a try if you wish. 
So now I'm going to close the issue. 

If you think the problem is really caused by angular-sse-client, please reopen it, and provie more information.
thanks

**Closed as completed by QueenKunkun** 2020-12-09 06:17 UTC
